<?php

namespace MauticPlugin\LeuchtfeuerCompanySegmentsBundle\Tests\EventListener;

use Mautic\CoreBundle\Entity\AuditLog;
use Mautic\CoreBundle\Model\AuditLogModel;
use Mautic\CoreBundle\Test\MauticMysqlTestCase;
use MauticPlugin\LeuchtfeuerCompanySegmentsBundle\Entity\CompanySegment;
use MauticPlugin\LeuchtfeuerCompanySegmentsBundle\Model\CompanySegmentModel;
use MauticPlugin\LeuchtfeuerCompanySegmentsBundle\Tests\Support\ActivePluginTrait;

class AuditLogSubscriberTest extends MauticMysqlTestCase
{
    use ActivePluginTrait;
    private AuditLogModel $auditLogModel;
    private CompanySegmentModel $companySegmentModel;

    private int $baseTotalRows = 0;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->activePlugin();
        $this->useCleanupRollback = false;
        $this->setUpSymfony($this->configParams);
        $this->auditLogModel = self::getContainer()->get('mautic.core.model.auditlog');
        assert($this->auditLogModel instanceof AuditLogModel);
        $this->companySegmentModel = self::getContainer()->get('mautic.company_segments.model.company_segment');
        assert($this->companySegmentModel instanceof CompanySegmentModel);
        $this->baseTotalRows = count($this->auditLogModel->getRepository()->findAll());
    }

    public function testAuditLogSubscriber(): void
    {
        $companySegment = $this->createCompanySegmentAndCheckAuditLog();
        $companySegment = $this->updateCompanySegmentAndCheckAuditLog($companySegment);
        $this->deleteCompanySegmentAndCheckAuditLog($companySegment);
    }

    private function createCompanySegmentAndCheckAuditLog(): CompanySegment
    {
        $auditLogResultBefore = $this->auditLogModel->getRepository()->findAll();
        $this->assertCount($this->baseTotalRows, $auditLogResultBefore, 'Audit log should be empty before creating a company segment');

        $companySegment = new CompanySegment();
        $companySegment->setName('Test Segment');
        $companySegment->setDescription('This is a test segment');
        $companySegment->setAlias('test_segment');
        $companySegment->setIsPublished(true);
        $this->companySegmentModel->saveEntity($companySegment);

        $auditLogResultAfter = $this->auditLogModel->getRepository()->findAll();
        $this->assertCount($this->baseTotalRows + 1, $auditLogResultAfter, 'Audit log should contain one entry after creating a company segment');
        $lastLog = end($auditLogResultAfter);
        assert($lastLog instanceof AuditLog);
        self::assertEquals('company_segment', $lastLog->getObject());
        self::assertEquals('added', $lastLog->getAction());
        self::assertEquals($companySegment->getId(), $lastLog->getObjectId());

        return $companySegment;
    }

    private function updateCompanySegmentAndCheckAuditLog(CompanySegment $companySegment): CompanySegment
    {
        $auditLogResultBefore = $this->auditLogModel->getRepository()->findAll();
        $this->assertCount($this->baseTotalRows + 1, $auditLogResultBefore, 'Audit log should contain one entry before updating a company segment');

        $companySegment->setName('Updated Segment Name');
        $this->companySegmentModel->saveEntity($companySegment);

        $auditLogResultAfter = $this->auditLogModel->getRepository()->findAll();
        $this->assertCount($this->baseTotalRows + 2, $auditLogResultAfter, 'Audit log should contain one more entry after updating a company segment');
        $lastLog = end($auditLogResultAfter);
        assert($lastLog instanceof AuditLog);
        self::assertEquals('company_segment', $lastLog->getObject());
        self::assertEquals('updated', $lastLog->getAction());
        self::assertEquals($companySegment->getId(), $lastLog->getObjectId());

        return $companySegment;
    }

    private function deleteCompanySegmentAndCheckAuditLog(CompanySegment $companySegment): void
    {
        $auditLogResultBefore = $this->auditLogModel->getRepository()->findAll();
        $this->assertCount($this->baseTotalRows + 2, $auditLogResultBefore, 'Audit log should contain one entry before deleting a company segment');

        $this->companySegmentModel->deleteEntity($companySegment);

        $auditLogResultAfter = $this->auditLogModel->getRepository()->findAll();
        $this->assertCount($this->baseTotalRows + 3, $auditLogResultAfter, 'Audit log should contain one more entry after deleting a company segment');
        $lastLog = end($auditLogResultAfter);
        assert($lastLog instanceof AuditLog);
        self::assertEquals('company_segment', $lastLog->getObject());
        self::assertEquals('deleted', $lastLog->getAction());
        self::assertEquals($companySegment->getId(), $lastLog->getObjectId());
    }
}
